### ISSUE TITLE
Spawn EACCES error

### ISSUE THREAD

**Issue by heapwolf** [cjntaylor/node-cmake#10]
npm install just outputs `Error: spawn EACCES`.
- os Darwin 15.3.0 Darwin Kernel Version 15.3.0
- node v4.3.1
- npm 2.14.12

**Comment by cjntaylor** [comment]
That suggests that you're running into permissions issues with either ncmake or cmake itself. Does "sudo npm install" produce an error? What do these produce?

```
ls -alh `which cmake`
ls -alh `which ncmake`
```

**Comment by heapwolf** [comment]
``` bash
%ls -alh `which cmake`
lrwxr-xr-x  1 0x00a  admin    31B Feb 17 11:10 /usr/local/bin/cmake@ -> ../Cellar/cmake/3.4.1/bin/cmake
```

``` bash
%ls -alh `which ncmake`
lrwxr-xr-x  1 0x00a  admin    44B Apr  7 10:27 /usr/local/bin/ncmake@ -> ../lib/node_modules/node-cmake/lib/ncmake.js
```

**Comment by cjntaylor** [comment]
Hmm, odd. That permission set looks valid. The only place that would generate that error code in node-cmake itself would be in ncmake, when `child_process.spawn` is called to kick off the cmake generation. Does this cause the same error when running it as a normal user in your module folder?

`node -e "require('child_process').spawn('cmake', ['--version'], { stdio: 'inherit' })"`

If it is successful, it should output the cmake version.

**Comment by cjntaylor** [comment]
Oh actually, I take that back slightly. That '@' symbol on the end of those symlinks suggests that OSX has set extended permissions for those files. That symbol can indicate that OSX has quarantine permissions set, which prevents execution. 

Looking at the paths I'm assuming this is via homebrew, which I'm not accustomed to having this problem. Are you running on El Capitan? There are apparently changes in that version that break homebrew in general:

http://digitizor.com/fix-homebrew-permissions-osx-el-capitan

**Comment by cjntaylor** [comment]
Closing for lack of response

**Comment by heapwolf** [comment]
I installed cmake-js and it worked fine.

**Comment by cjntaylor** [comment]
But node-cmake still doesn't work? What happens when you run the following:

`node -e "require('child_process').spawn('cmake', ['--version'], { stdio: 'inherit' })"`

**Comment by cjntaylor** [comment]
Closing again for lack of response. 

2.0 release also simplifies these calls and should behave as expected. Re-open if you're still having issues, but post debug logs / output from execution so I can triage.
