### ISSUE TITLE
npm release contains unecessary binaries.

### ISSUE THREAD

**Issue by tedbrandston** [cjntaylor/node-cmake#11]
under example there is an 'out' folder containing some mac build products. The extra space taken is a minor annoyance, but on our windows build machines the very long paths produced (> 260 characters) cause problems for some build scripts.
We have a workaround (a hack to delete that folder partway through a build) but would it be possible to remove those, either from this or the next release?

**Comment by cjntaylor** [comment]
Apologies for that, the folder was never intended to be included in the first place, escaped me during publish cleanup. I've pushed and published a new version, 1.2.1 (0dee2b3d23265789905a35fa4bbab99964b346e9) that should have removed these files. Let me know if the files persist.
