### ISSUE TITLE
Detect node headers in nvm directory

### ISSUE THREAD

**Issue by TheMarex** [cjntaylor/node-cmake#14]
Instead of downloading headers at configuration time it would be great if existing node headers would be detected if they are placed in `~/.nvm/versions/node/$(nvm current)/include`.

**Comment by cjntaylor** [comment]
This tool is intended to be cross platform; a big part of the rewrite was streamlining and simplifying the design. NVM isn't supported on windows, so this isn't very high priority to me. I'll add it to the backlog of changes to consider, but don't hold your breath.

You're welcome to make the change yourself and issue a pull request (against dev). This would belong in the NodeJS.cmake; a bit of refactoring to make the download optional and some logic for defining the header locations from nvm.
