### ISSUE TITLE
Build fails if NODEJS_LINK_FLAGS (LINK_FLAGS) is empty

### ISSUE THREAD

**Issue by jbadorek** [cjntaylor/node-cmake#27]
I see the change to use set_target_properties for LINK_FLAGS, but if the parent scope LINK_FLAGS is empty (and thus NODEJS_LINK_FLAGS is empty), set_target_properties fails.

```
CMake Error at node_modules/node-cmake/NodeJS.cmake:609 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

**Comment by cjntaylor** [comment]
Sorry about that, I've pushed a fix in 2.3.1 that should address this and the space separation issue.
