### ISSUE TITLE
Configuring a cmake project with different parameters has no effect

### ISSUE THREAD

**Issue by kirbysayshi** [cjntaylor/node-cmake#29]
This might be my lack of cmake experience, but I believe cache values are not being overridden in the case of defaults vs CLI cmake values.

If you have a CMakeLists.txt like:

```
nodejs_init()

# For the sake of debugging.
message(STATUS "NODEJS_BINARY: ${NODEJS_BINARY}")
message(STATUS "NODEJS_VERSION: ${NODEJS_VERSION}")
message(STATUS "NODEJS_SOURCES: ${NODEJS_SOURCES}")
message(STATUS "NODEJS_INCLUDE_DIRS: ${NODEJS_INCLUDE_DIRS}")
message(STATUS "NODEJS_LIBRARIES: ${NODEJS_LIBRARIES}")
message(STATUS "NODEJS_LINK_FLAGS: ${NODEJS_LINK_FLAGS}")
message(STATUS "NODEJS_DEFINITIONS: ${NODEJS_DEFINITIONS}")
```

And you run it:

```
$ cmake .. -GXcode

...

-- NodeJS: Using node, version v7.6.0
-- NODEJS_BINARY: /Users/XXXXX/nvm/versions/node/v7.6.0/bin/node
-- NODEJS_VERSION: v7.6.0
-- NODEJS_SOURCES:
-- NODEJS_INCLUDE_DIRS: /Users/XXXXX/dev/XXPROJECTXX/build/node/v7.6.0/include
-- NODEJS_LIBRARIES:
-- NODEJS_LINK_FLAGS: -undefined dynamic_lookup
-- NODEJS_DEFINITIONS: _LARGEFILE_SOURCE;_FILE_OFFSET_BITS=64;_DARWIN_USE_64_BIT_INODE=1
```

Looks good. If you then decide to build for electron:

```
$ cmake .. -GXcode -DCODE_COVERAGE=0 -DNODEJS_NAME=iojs -DNODEJS_VERSION=v1.6.4 -DNODEJS_URL=https://atom.io/download/atom-shell

...

-- NodeJS: Using iojs, version v1.6.4
-- NODEJS_BINARY: /Users/XXXXX/nvm/versions/node/v7.6.0/bin/node
-- NODEJS_VERSION: v1.6.4
-- NODEJS_SOURCES:
-- NODEJS_INCLUDE_DIRS: /Users/XXXXX/dev/XXPROJECTXX/build/iojs/v1.6.4/include
-- NODEJS_LIBRARIES:
-- NODEJS_LINK_FLAGS: -undefined dynamic_lookup
-- NODEJS_DEFINITIONS: _LARGEFILE_SOURCE;_FILE_OFFSET_BITS=64;_DARWIN_USE_64_BIT_INODE=1
```

Notice how NODEJS_BINARY is pointing to the old value?

And finally, if you then later build for just node again, you'll still have the same Electron values:

```
$ cmake .. -GXcode

...

-- NodeJS: Using iojs, version v1.6.4
-- NODEJS_BINARY: /Users/XXXXX/nvm/versions/node/v7.6.0/bin/node
-- NODEJS_VERSION: v1.6.4
-- NODEJS_SOURCES:
-- NODEJS_INCLUDE_DIRS: /Users/XXXXX/dev/XXPROJECTXX/build/iojs/v1.6.4/include
-- NODEJS_LIBRARIES:
-- NODEJS_LINK_FLAGS: -undefined dynamic_lookup
-- NODEJS_DEFINITIONS: _LARGEFILE_SOURCE;_FILE_OFFSET_BITS=64;_DARWIN_USE_64_BIT_INODE=1
```

I'm guessing this is because CLI values take precedent over uninitialized defaults. But it's definitely a gotcha. Once the NAME/VERSION/URL is set on the command line, all of those params must be unset (via `-U`) or given something reasonable.

Or am I doing it wrong?

**Comment by cjntaylor** [comment]
This has to do with how CMake caches values (CMake makes heavy use of several cache files in the `build` directory). I can look into some sort of cache-breaking approach here to address this, although it runs counter to typical CMake conventions (CMake assumes you configure implicitly once; all subsequent configurations will be explicit). You can work around this by always specifying the `-D` flags, or by using `ncmake`, which always specifies these parameters when needed.

Looking at `${NODEJS_BINARY}` isn't particularly relevant, though. Its set to the currently installed version of node (if there is one on your system), and is only used if the binary exists and no other version or target environment is specified (or explicitly if you use the special version 'installed') to determine the version to use. It's not used at all during compilation; binaries (.lib files) are only needed for linking on windows; and a separate variable holds those values (`${NODEJS_LIBRARIES}` if memory serves).

**Comment by kirbysayshi** [comment]
Ok, I understand. I guess what I find weird about this is that due to the order of my steps, configuration succeeds. But if I wanted to go electron followed by nodejs, then it would fail without a lot of information as to why. But I understand this is more cmake than node-cmake.

Initially this issue arose because I was extracting the ABI/NODE_MODULE_VERSION from the downloaded headers, and of course those paths were being cached between runs too. This meant that I'd configure the build for node, then electron, but the ABI would still be node! Very confusing. All because I was using `find_file`. The solution was to `unset` the `find_file` destination variable at the end of my cmake file.

BTW, I can't really use ncmake because my project is actually first a cpp project that just happens to have node bindings, vs the other way around.

**Comment by kirbysayshi** [comment]
In case anyone is wondering about extracting NODE_MODULE_VERSION (I use it for the built artifact name, to ensure there is no mismatch when node `require`s it):

```
# Attempt to extract the ABI version from the fetched node headers
# to use in the addon filename.
find_file(
  NODEJS_NODEVERSION_PATH NAMES
  "node_version.h"
  PATHS ${NODEJS_INCLUDE_DIRS})
execute_process(
  COMMAND grep "-oEhr" "NODE_MODULE_VERSION (\\d+)" "${NODEJS_NODEVERSION_PATH}"
  RESULT_VARIABLE NMV_GREP_RESULT
  OUTPUT_VARIABLE NMV_GREP_OUTPUT
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REPLACE "NODE_MODULE_VERSION " "" NODEJS_ABI_VERSION ${NMV_GREP_OUTPUT})
if(NOT NMV_GREP_RESULT STREQUAL "0")
  message(
    FATAL_ERROR
    "Could not retrieve ABI compatibility version \
    from ${NODEJS_NODEVERSION_PATH}")
endif()

# do something with it, like use it in a copy command POST_BUILD

unset(NODEJS_NODEVERSION_PATH CACHE)
```

**Comment by cjntaylor** [comment]
You could also do this with pure cmake (untested):

```cmake
set(NODEJS_NODEVERSION_MATCH "NODE_MODULE_VERSION[ \t]+([0-9]+)")
find_file(NODEJS_NODEVERSION_PATH
  NAMES "node_version.h"
  PATHS ${NODEJS_INCLUDE_DIRS}
)
file(STRINGS 
  ${NODEJS_NODEVERSION_PATH} NODEJS_ABI_VERSION
  REGEX ${NODEJS_NODEVERSION_MATCH}
  LIMIT_COUNT 1
)
if(NOT NODEJS_ABI_VERSION)
message(FATAL_ERROR
    "Could not retrieve ABI compatibility version from ${NODEJS_NODEVERSION_PATH}"
)
endif()
string(REGEX MATCH ${NODEJS_NODEVERSION_MATCH} NODEJS_ABI_VERSION ${NODEJS_ABI_VERSION})
set(NODEJS_ABI_VERSION ${CMAKE_MATCH_1})
unset(NODEJS_NODEVERSION_PATH CACHE)
```
The benefit is that you don't need grep installed on the system for this to work (won't normally be the case on windows), and it doesn't need to be in your path.

If you really want to do the above, at least use `find_program(GREP_BINARY NAMES grep)` and `${GREP_BINARY}` in execute_process so that it explicitly finds the binary path.

**Comment by kirbysayshi** [comment]
@cjntaylor this is great! Thank you very much for the code, it seems to work perfectly!
