### ISSUE TITLE
2.5.0 breaks compat with Node 4 & 5

### ISSUE THREAD

**Issue by markandrus** [cjntaylor/node-cmake#38]
Hi,

First of all, thanks very much for this project! I'm using this over at js-platform/node-webrtc.

We still claim support for Node 4 and 5. Granted, Node's [Release schedule](https://github.com/nodejs/Release#release-schedule) states that Node 5 is "End-of-life", but Node 4 is marked "Maintenance LTS" until 2018-04-30.

node-cmake 2.5.0 appears to break compatibility with Node 4 and 5 due to the issue below. Would you consider rewriting this change and releasing a 2.5.1? Otherwise, I may need to cut a patch release pinning to an earlier node-cmake release.

```
Running ncmake configure --debug
/home/travis/build/js-platform/node-webrtc/node_modules/node-cmake/lib/ncmake.js:10
let argparse = yargs
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

Mark

**Comment by cjntaylor** [comment]
Whoops 😅 

I updated to ES6 syntax without thinking much about this, but I absolutely want to support the maintenance LTS. I'll release a 2.5.1 hotfix shortly.

**Comment by cjntaylor** [comment]
And done! 2.5.1 reverts any ES6 syntax I used back to ES5. In the future, I may add a conversion step since I'm accustomed to the ES6 syntax at this point, but this should be ok for now. Let me know if you run into any other issues.
