### ISSUE TITLE
Work with electron beta version like v2.0.0-beta.1

### ISSUE THREAD

**Issue by toddwong** [cjntaylor/node-cmake#39]
The version string `v2.0.0-beta.1` breaks the `HEADERS_MATCH` regular expression:

```
set(HEADERS_MATCH "^([A-Fa-f0-9]+)[ \t]+([^-]+)-(headers|v?[0-9.]+)-(headers|v?[0-9.]+)([.]tar[.]gz)$")
```

The content of the SHASUMS.txt

```
dc6b365c1d2df25205c878e4ecd3e3106cedf2a1  node-v2.0.0-beta.1.tar.gz
337cdeea1c4dadc4c20d688c464bc6223fb9f342  iojs-v2.0.0-beta.1.tar.gz
36c4707de00b044e309c10a67721206a45d632dd  iojs-v2.0.0-beta.1-headers.tar.gz
44adb76edc7eb84f52eab0fb29a73dcc7183bec5  node.lib
555d30c34f09ba2c656745cd4940c24eace0db58  x64/node.lib
44adb76edc7eb84f52eab0fb29a73dcc7183bec5  win-x86/iojs.lib
555d30c34f09ba2c656745cd4940c24eace0db58  win-x64/iojs.lib
```

**Comment by cjntaylor** [comment]
Herm, I'll have to do some tinkering with the expression to allow this. CMake regex expressions are fairly limited in functionality.

As a very, very, rough guess, can you replace that variable with the following:

```
set(HEADERS_MATCH "^([A-Fa-f0-9]+)[ \t]+([^-]+)-(headers|v?[0-9.]+-?.*)-(headers|v?[0-9.]+-?.*)([.]tar[.]gz)$")
```
The extra little expression at the end should allow it to capture `-beta.1` as part of the version identifier. I'll have to do some more testing to make sure this doesn't break other strings before making the change though.

**Comment by toddwong** [comment]
I work it around by parsing every line manually for now.
BTW, in which scenario is it `xxx-headers-1.2.3.tar.gz ` instead of `xxx-1.2.3-headers.tar.gz`?

**Comment by toddwong** [comment]
How about this one?

```
    set(HEADERS_MATCH "^([A-Fa-f0-9]+)[ \t]+(([^-]+)-((.+)-headers|headers-(.+))[.]tar[.]gz)$")
```

```
    set(HEADERS_CHECKSUM ${CMAKE_MATCH_1})
    set(NAME ${CMAKE_MATCH_3})
    if(CMAKE_MATCH_5)
        set(VERSION ${CMAKE_MATCH_5})
    else()
        set(VERSION ${CMAKE_MATCH_6})
    endif()
    set(HEADERS_ARCHIVE ${CMAKE_MATCH_2})
```

**Comment by toddwong** [comment]
Checked the node-gyp code, only `xxx-1.2.3-headers.tar.gz` is supported.

```
  tarballUrl = url.resolve(baseUrl, name + '-v' + version + (canGetHeaders ? '-headers' : '') + '.tar.gz')
```

https://github.com/nodejs/node-gyp/blob/241752f381b0b68b995526b3808217e185c3e9fb/lib/process-release.js#L118

So, the following may be enough

```
set(HEADERS_MATCH "^([A-Fa-f0-9]+)[ \t]+(([^-]+)-(.+)-headers[.]tar[.]gz)$")
```

Not sure if it is necessary to parse and validate the version string (according to Semantic Versioning specification).

**Comment by computerquip-streamlabs** [comment]
I've made a PR for this [here](https://github.com/cjntaylor/node-cmake/pull/49). Seems to work for electron `v3.0.0-beta.1` which works for me. I did some quick testing with older versions of node and it seems to work alright. Anything before Node 4.0.0 I guess is technically dropped with that however. 

EDIT: I also didn't test with nw.js but should work with them as well.

**Comment by computerquip-streamlabs** [comment]
This issue shouldn't have been closed. Can this be re-opened or my PR pulled/critiqued?
