### ISSUE TITLE
how to add dependencies ?

### ISSUE THREAD

**Issue by sancelot** [cjntaylor/node-cmake#48]
Hi,

Some cpp files are created by swig.

howto add these files as dependencies , since they are generated by swig .

Regards,
S.Ancelot

**Comment by cjntaylor** [comment]
This request is out of scope for this project, but a few things I'd suggest:

Swig generates source files that need to be linked into your module. Sources can be added to a list prior to calling `add_nodejs_module`, e.g:

```
list(APPEND MY_SOURCES
  module.c
  generated_file_1.h
  generated_file_1.cpp
  generated_file_2.h
  generated_file_2.cpp
)
add_nodejs_module(${PROJECT_NAME} ${MY_SOURCES})
```
 
From what I can see, cmake provides two built-in modules for swig `FindSwig.cmake` and `UseSwig.cmake`. Annoyingly, these modules provide functions attempt to build the entire library all at once. These functions serve the same role as `add_nodejs_module`; you won't be able to use them together. What you need is the list of generated sources that this module produces, and then pass this list into `add_nodejs_module` as sources. However, I don't know if you can hack around the built-in modules, as they don't seem to support javascript as a language target (which makes sense, its a relatively new target for swig).

I wish I could be more helpful, but most folks don't use swig when writing node bindings, they manually write bindings by hand.

https://cmake.org/cmake/help/v3.5/module/FindSWIG.html
https://cmake.org/cmake/help/v3.5/module/UseSWIG.html

https://github.com/Kitware/CMake/blob/master/Modules/FindSWIG.cmake
https://github.com/Kitware/CMake/blob/master/Modules/UseSWIG.cmake

P.S. In that last link, the function `SWIG_ADD_SOURCE_TO_MODULE` looks like almost what you want to do (you'd call it with the same target as `add_nodejs_module`, that is, the first argument you pass to my function and each `*.i` file you want to generate), but the context it's called in does a lot more than just call it, so you'd have to figure out what else needs to be replicated. Also, I don't quite remember how CMake scopes modules right now. You may not even be able to call that function from your own file ~YMMV.
