### ISSUE TITLE
Major flaw in path searching

### ISSUE THREAD

**Issue by Lokomojo** [cjntaylor/node-cmake#56]
"module.parent.filename" is only accurate the first time node-cmake is included.

This means that if node-cmake is used in two different modules which are used in the same project, the second one fails to find the native module.

**Comment by juanborre** [comment]
+1 to this.

if you have a package using node-cmake, it will create the compiled files in `node_modules/some_package/build`

When requiring the `some_package` from the main repo, it fails to find the native module.

This does not happen when the `some_package` is run on its own.

If you execute the following command: `cp -rf node_modules/some_package/build .`, then the code works and it finds the native module.

There is a problem with the include paths when node-cmake is required by several packages within the same repo.
