### ISSUE TITLE
Linker errors on Windows / MSVC2015

### ISSUE THREAD

**Issue by KrishnaPG** [cjntaylor/node-cmake#6]
Looks like the Node libraries are not being linked to the target in the CMake.

Getting linker errors on Windows with MSVC2015.

Using the below line in the `CMakeLists.txt` resolves the problem, but it would be great if`add_nodejs_module` method itself takes care of it.

```
  target_link_libraries(${PROJECT_NAME}  ${NodeJS_LIBRARIES})
```

**Comment by cjntaylor** [comment]
Fixed in v1.2.0
