### ISSUE TITLE
Should have a dependency on the CMakeLists.txt

### ISSUE THREAD

**Issue by KrishnaPG** [cjntaylor/node-cmake#8]
So that when the CMakeLists.txt is modified, the configuration is re-run (to regenerate the solution/project files) and re-built. (Helpful in the dev cycle)

Right now, `ncmake --build` does not respect the modifications to the CMakeLists and just verifies only the targets validity.

**Comment by cjntaylor** [comment]
All generators for cmake automatically check to see if the build has been modified in any way before executing the build and re-run cmake as needed. There is no need for ncmake to handle this functionality.
